controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    # Arckermann steering controller
    # ackermann_steering_cont:
    #   type: ackermann_steering_controller/AckermannSteeringController
      
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster  

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    # forward_velocity_controller:
    #   type: forward_command_controller/ForwardCommandController

    # forward_position_controller:
    #   type: forward_command_controller/ForwardCommandController

# forward_velocity_controller:
#   ros__parameters:
#     joints:
#       # - left_front_wheel_joint
#       # - right_front_wheel_joint
#       - left_rear_wheel_joint
#       - right_rear_wheel_joint      
#     interface_name: velocity
#     command_interfaces:
#       - velocity
#     state_interfaces:
#       - position
#       - velocity

# forward_position_controller:
#   ros__parameters:
#     joints:
#       - left_steer_joint
#       - right_steer_joint
#     interface_name: position
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity

# ackermann_steering_cont:
#   ros__parameters:
#     reference_timeout: 1.0
#     front_steering: true
#     # rear_wheels_names: ["left_rear_wheel_joint", "right_rear_wheel_joint"]
#     # front_wheels_names: ["left_steer_joint", "right_steer_joint"]
#     rear_wheels_names: ["right_rear_wheel_joint", "left_rear_wheel_joint"]
#     front_wheels_names: ["right_steer_joint", "left_steer_joint"]
#     open_loop: true
#     base_frame_id: "base_link"
#     odom_frame_id: "odom"
#     enable_odom_tf: true
#     reduce_wheel_speed_until_steering_reached: true
#     use_stamped_vel: false

#     front_wheel_track: 0.287
#     rear_wheel_track: 0.287
#     front_wheels_radius: 0.05
#     rear_wheels_radius: 0.05
#     wheelbase: 0.38

    

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_rear_wheel_joint"]
    right_wheel_names: ["right_rear_wheel_joint"]

    wheel_separation: 0.21
    wheel_radius: 0.05

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    position_feedback: false
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5 # seconds
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    linear.x.max_velocity: .NAN
    linear.x.min_velocity: .NAN
    linear.x.max_acceleration: .NAN
    linear.x.max_deceleration: .NAN
    linear.x.max_acceleration_reverse: .NAN
    linear.x.max_deceleration_reverse: .NAN
    linear.x.max_jerk: .NAN
    linear.x.min_jerk: .NAN

    angular.z.max_velocity: .NAN
    angular.z.min_velocity: .NAN
    angular.z.max_acceleration: .NAN
    angular.z.max_deceleration: .NAN
    angular.z.max_acceleration_reverse: .NAN
    angular.z.max_deceleration_reverse: .NAN
    angular.z.max_jerk: .NAN
    angular.z.min_jerk: .NAN




